import fs from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const gameDir = path.join(root, "images", "game");
const outputFile = path.join(root, "game-data.js");
const imageExtPattern = /\.(jpe?g|png|webp)$/i;

const files = (await walkImages(gameDir))
  .map((file) => file.split(path.sep).join("/"))
  .sort((a, b) => a.localeCompare(b, "zh-Hans-CN"));

const sets = [
  {
    id: "teacher-photo",
    title: "根据老师小时候照片猜老师",
    prompt: "这是哪位老师？",
    tag: "照片猜老师",
    mode: "direct",
    match: isTeacherPhoto
  },
  {
    id: "teacher-item",
    title: "根据老师私人物品猜老师姓名",
    prompt: "这件物品属于哪位老师？",
    tag: "物品猜老师",
    mode: "focus",
    match: isTeacherItem
  },
  {
    id: "classroom",
    title: "根据照片猜学科教室",
    prompt: "这是哪间学科教室？",
    tag: "教室猜一猜",
    mode: "direct",
    match: isClassroom
  }
].map(({ match, ...set }) => ({
  ...set,
  questions: files
    .filter(match)
    .map((file) => ({
      image: `images/game/${file}`,
      answer: deriveAnswer(file)
    }))
}));

const payload = `// This file is generated by tools/generate_game_data.mjs.\n// Add or remove image files in images/game/, then run: node tools/generate_game_data.mjs\nwindow.GAME_DATA = ${JSON.stringify(sets, null, 2)};\n`;

await fs.writeFile(outputFile, payload, "utf8");
console.log(`Generated ${path.relative(root, outputFile)} with ${files.length} images.`);

async function walkImages(dir, base = dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const found = [];
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...await walkImages(abs, base));
    } else if (entry.isFile() && imageExtPattern.test(entry.name)) {
      found.push(path.relative(base, abs));
    }
  }
  return found;
}

function isClassroom(name) {
  return /教室/.test(name) || /^[A-Z]\d{3}\b/i.test(stripExt(path.basename(name)));
}

function isTeacherItem(name) {
  return /奖品|物品|私人物品/.test(name);
}

function isTeacherPhoto(name) {
  return !isClassroom(name) && !isTeacherItem(name);
}

function stripExt(name) {
  return name.replace(/\.[^.]+$/, "");
}

function deriveAnswer(file) {
  return decodeURIComponent(stripExt(path.basename(file)))
    .replace(/^已移除背景的/, "")
    .replace(/\s+\d+$/, "")
    .replace(/老师的物品$/, "老师")
    .replace(/老师的奖品$/, "老师")
    .replace(/的物品$/, "")
    .replace(/的奖品$/, "")
    .trim();
}
