import fs from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const gameDir = path.join(root, "images", "game");
const outputFile = path.join(root, "game-data.js");
const imageExtPattern = /\.(jpe?g|png|webp)$/i;

const entries = await fs.readdir(gameDir, { withFileTypes: true });
const files = entries
  .filter((entry) => entry.isFile() && imageExtPattern.test(entry.name))
  .map((entry) => entry.name)
  .sort((a, b) => a.localeCompare(b, "zh-Hans-CN"));

const sets = [
  {
    id: "teacher-photo",
    title: "根据照片猜老师姓名",
    prompt: "这是哪位老师？",
    tag: "照片猜老师",
    match: (name) => !isClassroom(name) && !isTeacherItem(name)
  },
  {
    id: "teacher-item",
    title: "根据老师私人物品猜老师姓名",
    prompt: "这件物品属于哪位老师？",
    tag: "物品猜老师",
    match: isTeacherItem
  },
  {
    id: "classroom",
    title: "根据照片猜学科教室",
    prompt: "这是哪间学科教室？",
    tag: "教室猜一猜",
    match: isClassroom
  }
].map(({ match, ...set }) => ({
  ...set,
  questions: files
    .filter(match)
    .map((file) => ({
      image: `images/game/${file}`,
      answer: deriveAnswer(file)
    }))
}));

const payload = `// This file is generated by tools/generate_game_data.mjs.\n// Add or remove image files in images/game/, then run: node tools/generate_game_data.mjs\nwindow.GAME_DATA = ${JSON.stringify(sets, null, 2)};\n`;

await fs.writeFile(outputFile, payload, "utf8");
console.log(`Generated ${path.relative(root, outputFile)} with ${files.length} images.`);

function isClassroom(name) {
  return /^[A-Z]\d{3}\b/i.test(stripExt(name));
}

function isTeacherItem(name) {
  return /奖品|物品|私人物品/.test(name);
}

function stripExt(name) {
  return name.replace(/\.[^.]+$/, "");
}

function deriveAnswer(file) {
  return decodeURIComponent(stripExt(file))
    .replace(/^已移除背景的/, "")
    .replace(/\s+\d+$/, "")
    .replace(/老师的奖品$/, "老师")
    .replace(/的奖品$/, "")
    .trim();
}
